/*
 * generated by Xtext 2.12.0
 */
package se.gu.co4robots.xtext.promise.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPromiseScopeProvider extends DelegatingScopeProvider {
}
