/*
 * generated by Xtext 2.12.0
 */
package se.gu.co4robots.xtext.promise.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import promise.Mission

@RunWith(XtextRunner)
@InjectWith(PromiseInjectorProvider)
class PromiseParsingTest {
	@Inject
	ParseHelper<Mission> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
