/**
 * generated by Xtext 2.12.0
 */
package se.gu.co4robots.xtext.promise.scoping;

import se.gu.co4robots.xtext.promise.scoping.AbstractPromiseScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PromiseScopeProvider extends AbstractPromiseScopeProvider {
}
