Robots [ r1,r2, ]
Events [ intruder description of event intruder,found_object description of event  found_object,help_requested description of event  help_requested,r1_low_battery description of event  r1_low_battery,r2_low_battery description of event  r2_low_battery,finish description of event  finish, ]
Actions [ raise_alarm description of action raise_alarm,request_help description of action  request_help,grasp_object description of action  grasp_object,release_object description of action  release_object,charge_battery description of action  charge_battery, ]
StoppingEvents [ {r1,[] (<> ((l1) && <> ((l2) && <> ((l3)))))),finish} ]
