<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="promise" nsURI="http://gu.se/co4robots.promise" nsPrefix="co4robots.promise">
  <eClassifiers xsi:type="ecore:EClass" name="Operator" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectingEvent" upperBound="-1"
        eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//CompositionOperator"
        eOpposite="#//CompositionOperator/inputOperators"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FallBackOp" eSuperTypes="#//CompositionOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceOp" eSuperTypes="#//CompositionOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelOp" eSuperTypes="#//CompositionOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventHandlerOp" eSuperTypes="#//CompositionOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputObservedEvents" upperBound="-1"
        eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionOp" eSuperTypes="#//CompositionOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEvents" upperBound="-1"
        eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" lowerBound="1"
        upperBound="-1" eType="#//Operator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="robots" lowerBound="1"
        upperBound="-1" eType="#//Robot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        upperBound="-1" eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositionOperator" abstract="true"
      eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputOperators" upperBound="-1"
        eType="#//Operator" containment="true" eOpposite="#//Operator/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Robot" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DelegateOp" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputLocations" upperBound="-1"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputRobot" lowerBound="1"
        upperBound="-1" eType="#//Robot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="#//Pattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputAction" upperBound="-1"
        eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stoppingEvent" upperBound="-1"
        eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="MovementPatterns" abstract="true" eSuperTypes="#//Pattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="Visit" eSuperTypes="#//MovementPatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequencedVisit" eSuperTypes="#//MovementPatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderderVisit" eSuperTypes="#//MovementPatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="StrictOrderedVisit" eSuperTypes="#//MovementPatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="FairVisit" eSuperTypes="#//MovementPatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="Patrolling" eSuperTypes="#//MovementPatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequencedPatrolling" eSuperTypes="#//MovementPatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedPatrolling" eSuperTypes="#//MovementPatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="StrictOreredPatrolling" eSuperTypes="#//MovementPatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="FairPatrolling" eSuperTypes="#//MovementPatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="AvoidancePatterns" abstract="true" eSuperTypes="#//Pattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpperRestrictedAvoidance" eSuperTypes="#//AvoidancePatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExactRestrictedAvoidance" eSuperTypes="#//AvoidancePatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="LowerRestrictedAvoidance" eSuperTypes="#//AvoidancePatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="FutureAvoidance" eSuperTypes="#//AvoidancePatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalAvoidance" eSuperTypes="#//AvoidancePatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="PastAvoidance" eSuperTypes="#//AvoidancePatterns"/>
  <eClassifiers xsi:type="ecore:EClass" name="TriggerPatterns" abstract="true" eSuperTypes="#//Pattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wait" eSuperTypes="#//TriggerPatterns">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayedReaction" eSuperTypes="#//TriggerPatterns">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstantReaction" eSuperTypes="#//TriggerPatterns">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="robot" upperBound="-1"
        eType="#//Robot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" upperBound="-1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedLocation" eSuperTypes="#//Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="NotOrderedLocation" eSuperTypes="#//Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleAction" eSuperTypes="#//Pattern"/>
</ecore:EPackage>
